packages:
  - apps/*
  - packages/*

catalog:
  "@eslint/js": 10.0.1
  "@next/eslint-plugin-next": 16.1.6
  "@types/node": 25.3.0
  eslint: 10.0.1
  eslint-plugin-react-hooks: 7.0.1
  prettier: 3.8.1
  prettier-plugin-organize-imports: 4.3.0
  prettier-plugin-tailwindcss: 0.7.2
  typescript: 5.9.3
  typescript-eslint: 8.56.0
