packages:
    - apps/*
    - packages/*

catalog:
    '@commitlint/cli': 20.4.2
    '@commitlint/config-conventional': 20.4.2
    '@eslint/js': 10.0.1
    '@next/eslint-plugin-next': 16.1.6
    '@storybook/addon-docs': 10.2.10
    '@storybook/addon-themes': 10.2.10
    '@storybook/react-vite': 10.2.10
    '@tailwindcss/postcss': 4.2.0
    '@tailwindcss/vite': 4.2.0
    '@testing-library/dom': 10.4.1
    '@testing-library/jest-dom': 6.9.1
    '@testing-library/react': 16.3.2
    '@types/node': 25.3.0
    '@types/react': 19.2.14
    '@types/react-dom': 19.2.3
    '@vitejs/plugin-react': 5.1.4
    '@vitest/coverage-v8': 4.0.18
    class-variance-authority: 0.7.1
    clsx: 2.1.1
    eslint: 10.0.1
    eslint-config-prettier: 10.1.8
    eslint-plugin-react-hooks: 7.0.1
    jsdom: 28.1.0
    lefthook: 2.1.1
    lucide-react: 0.575.0
    next: 16.1.6
    nx: 22.5.2
    prettier: 3.8.1
    prettier-plugin-organize-imports: 4.3.0
    prettier-plugin-tailwindcss: 0.7.2
    radix-ui: 1.4.3
    react: 19.2.4
    react-dom: 19.2.4
    storybook: 10.2.10
    tailwind-merge: 3.5.0
    tailwindcss: 4.2.0
    tw-animate-css: 1.4.0
    typescript: 5.9.3
    typescript-eslint: 8.56.0
    vite: 7.3.1
    vite-plugin-dts: 4.5.4
    vitest: 4.0.18

onlyBuiltDependencies:
    - esbuild
    - lefthook
    - nx
    - sharp
    - unrs-resolver
