import type { Metadata } from 'next';
import type { PropsWithChildren } from 'react';

import '../styles/globals.css';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app'
};

export default function RootLayout({ children }: PropsWithChildren) {
    return (
        <html lang="en">
            <body className="min-h-screen bg-background">{children}</body>
        </html>
    );
}
